accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.urls import reverse_lazy

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('login_success/', views.LoginSuccess.as_view(), name='login_success'),
    path('my-profile/', views.MyProfileView.as_view(), name="my_profile"),
    path('change-password/', views.ChangePasswordView.as_view(),
         name="change_password"),
    path('logout/', auth_views.LogoutView.as_view(template_name='common/logout.html',
                                                  extra_context={
                                                      'title': 'Logout',
                                                  }), name="logout"),


    path('applicant/dashboard/',
         views.ApplicantDashboardView.as_view(), name="applicant_dashboard"),
    path('institution/dashboard/',
         views.InstitutionDashboardView.as_view(), name="institution_dashboard"),

    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

applicant/urls.py
from django.urls import path
from . import views


app_name = "applicant"

urlpatterns = [
    path('profile/', views.ApplicantProfileView.as_view(),
         name="applicant_profile"),
    path('create/profile/', views.CreateApplicantProfileView.as_view(),
         name="create_applicant_profile"),
    path('edit/profile/<int:pk>/', views.EditApplicantProfileView.as_view(),
         name="edit_applicant_profile"),
    path('delete/profile/<int:pk>/', views.DeleteApplicantProfileView.as_view(),
         name="delete_applicant_profile"),

    path('application/status/<int:applicant_id>/', views.ApplicationStatusView.as_view(),
         name="application_status"),

    path('application/admit/card/', views.ApplicantAdmitCardView.as_view(),
         name="applicant_admit_card"),
]

applications/urls.py
from django.urls import path
from . import views


app_name = "applications"

urlpatterns = [
    path('apply/<int:applicant_id>/', views.ApplyApplicationView.as_view(),
         name="apply"),

    path('application/list/', views.ApplicationListView.as_view(),
         name="application_list"),

    path('application/delete/<int:pk>/', views.DeleteApplicationView.as_view(),
         name="application_delete"),

    path('ajax/load-subjects/', views.load_subjects, name='ajax_load_subjects'),







]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import HomeLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('applicant/', include('applicant.urls', namespace='applicant')),
    path('institution/', include('institution.urls', namespace='institution')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('transaction/', include('transaction.urls', namespace='transaction')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', HomeLoginView.as_view(), name="home_login"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False


admin.site.site_header = "VortiBD Admin"
admin.site.site_title = "VortiBD Admin Portal"
admin.site.index_title = "VortiBD to Finder Researcher Portal"

settings/urls.py
from django.urls import path
from . import views


app_name = "settings"

urlpatterns = [
    path('faq/', views.SiteFaqView.as_view(),
         name="site_faq"),

]

transaction/urls.py
from django.urls import path
from . import views


app_name = "transaction"

urlpatterns = [
    path('transaction-method/',
         views.TransactionMethodView.as_view(), name="transaction_method"),
    path('transaction-method/add/',
         views.AddTransactionMethodView.as_view(), name="add_transaction_method"),
    path('transaction-method/edit/<int:pk>/',
         views.EditTransactionMethodView.as_view(), name="edit_transaction_method"),

    path('transaction-method/delete/<int:pk>/',
         views.DeleteTransactionMethodView.as_view(), name="delete_transaction_method"),

    path('application/pay-fee/<int:application_id>/<int:institute_id>/', views.PayApplicationFeeView.as_view(),
         name="pay_application_fee"),

    path('applicant/payment-list/', views.ApplicantPaymentListView.as_view(),
         name="applicant_payment_list"),

    path('institute/payment-list/', views.InstitutePaymentListView.as_view(),
         name="institute_payment_list"),

    path('institute/payment/check/<int:id>/', views.InstitutePaymentCheckView.as_view(),
         name="institute_payment_check"),


    path('applicant/transaction/details/<int:transaction_id>/',
         views.TransactionDetailsView.as_view(), name='transaction_details')
]

applicant/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.


class ApplicantProfile(models.Model):
    GENDER_CHOICES = (
        ('1', 'Male'),
        ('2', 'Female'),
    )
    RELIGION_CHOICES = (
        ('Islam', 'Islam'),
        ('Hinduism', 'Hinduism'),
        ('Cristian', 'Cristian'),
        ('Buddhist', 'Buddhist'),
    )
    FREEDOM_FIGHTER_CHOICES = (
        ('No', 'No'),
        ('Yes', 'Yes'),
    )
    IS_AUTISM_CHOICES = (
        ('No', 'No'),
        ('Yes', 'Yes'),
    )
    owner = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name='user_applications')
    student_name = models.CharField(max_length=250)
    father_name = models.CharField(max_length=250)
    father_occupation = models.CharField(max_length=250)
    mother_name = models.CharField(max_length=250)
    mother_occupation = models.CharField(max_length=250)
    present_address = models.TextField()
    permanent_address = models.TextField()
    contact_number = models.CharField(max_length=20)
    email_address = models.EmailField(max_length=254, null=True, blank=True)
    birth_date = models.CharField(max_length=230)
    birth_id = models.CharField(max_length=250, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    religion = models.CharField(max_length=10, choices=RELIGION_CHOICES)
    blood_group = models.CharField(max_length=20)
    freedom_fighter_quota = models.CharField(
        max_length=150, choices=FREEDOM_FIGHTER_CHOICES, default="0")
    is_autism = models.CharField(
        max_length=150, choices=IS_AUTISM_CHOICES, default="0")
    height = models.FloatField(null=True, blank=True)
    local_guardian_name = models.CharField(
        max_length=250, null=True, blank=True)
    relation_with_applicant = models.CharField(
        max_length=255, null=True, blank=True)
    guardian_income = models.FloatField()
    student_pic = models.ImageField(upload_to="student")

    class Meta:
        verbose_name = 'Applicant Form'
        verbose_name_plural = '1. Applicant Form'

    def __str__(self):
        return self.student_name


class ApplicantPrevEducation(models.Model):
    BOARD_CHOICES = (
        ('Dhaka', 'Dhaka'),
        ('Khulna', 'Khulna'),
        ('Rajshahi', 'Rajshahi'),
        ('Rajshahi', 'Rajshahi'),
        ('Jessore', 'Jessore'),
        ('Comilla', 'Comilla'),
    )
    EXAM_CHOICES = (
        ('SSC', 'SSC'),
        ('HSC', 'HSC')
    )
    applicant = models.ForeignKey(
        ApplicantProfile, on_delete=models.CASCADE, related_name='applicant_pre_edu')
    exam_name = models.CharField(max_length=10, choices=EXAM_CHOICES)
    board_name = models.CharField(max_length=10, choices=BOARD_CHOICES)
    institute_name = models.CharField(max_length=255)
    passing_year = models.IntegerField()
    result = models.FloatField()

    def __str__(self):
        return self.applicant.student_name



@receiver(post_save, sender=ApplicantProfile)
def create_profile(sender, instance, created, **kwargs):
    print('signal','-----',sender)
    

applicant/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from .models import ApplicantPrevEducation, ApplicantProfile


class DateInput(forms.DateInput):
    input_type = 'date'


class ApplicantProfileForm(ModelForm):
    present_address = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))
    permanent_address = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))

    class Meta:
        model = ApplicantProfile
        exclude = ('owner',)
        widgets = {
            'birth_date': DateInput(),
        }


class ApplicantPrevEducationForm(ModelForm):
    class Meta:
        model = ApplicantPrevEducation
        fields = '__all__'


ApplicantPrevEducationFormSet = inlineformset_factory(
    ApplicantProfile, ApplicantPrevEducation, form=ApplicantPrevEducationForm, extra=1)

applicant/views.py
from django.shortcuts import redirect, get_object_or_404, HttpResponse
from django.urls import reverse_lazy
from django.db import transaction
from accounts.mixins import ActiveApplicantRequiredMixin
from django.contrib import messages
from django.core import serializers
from django.contrib.messages.views import SuccessMessageMixin
from applications.models import Application
from .forms import ApplicantPrevEducationFormSet, ApplicantProfileForm
from .models import ApplicantPrevEducation, ApplicantProfile
from django.views import generic
# Create your views here.


class ApplicantProfileView(generic.ListView):
    model = ApplicantProfile
    context_object_name = 'all_applicant_profile'
    template_name = 'applicant/applicant/all_applicant_profile.html'

    def get_queryset(self):
        qs = ApplicantProfile.objects.select_related(
            'owner').filter(owner=self.request.user).only("owner__username", "father_name", "mother_name", "student_name", "student_pic")
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Applicant Profile'
        return context


class CreateApplicantProfileView(SuccessMessageMixin, ActiveApplicantRequiredMixin, generic.CreateView):
    model = ApplicantProfile
    form_class = ApplicantProfileForm
    template_name = 'applicant/applicant/create_applicant_profile.html'
    success_message = "Applicant Profile was created successfully"
    success_url = reverse_lazy('applicant:applicant_profile')

    def get_context_data(self, **kwargs):
        context = super(CreateApplicantProfileView,
                        self).get_context_data(**kwargs)
        if self.request.POST:
            context['preveducation'] = ApplicantPrevEducationFormSet(
                self.request.POST, self.request.FILES)
        else:
            context['preveducation'] = ApplicantPrevEducationFormSet()
        context['title'] = 'Create Applicant Profile'
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        preveducation = context['preveducation']
        with transaction.atomic():
            if preveducation.is_valid():
                self.object = form.save(commit=False)
                self.object.owner = self.request.user
                self.object.save()
                preveducation.instance = self.object
                preveducation.save()
                return redirect('applicant:applicant_profile')
            else:
                return self.render_to_response(self.get_context_data(form=form))

class EditApplicantProfileView(SuccessMessageMixin, ActiveApplicantRequiredMixin, generic.UpdateView):
    model = ApplicantProfile
    context_object_name = 'applicant_profile'
    form_class = ApplicantProfileForm
    success_message = "Applicant Profile was updated successfully"
    template_name = 'applicant/applicant/update_applicant_profile.html'
    success_url = reverse_lazy('applicant:applicant_profile')

    def get_context_data(self, **kwargs):
        context = super(EditApplicantProfileView,
                        self).get_context_data(**kwargs)
        if self.request.POST:
            context['preveducation'] = ApplicantPrevEducationFormSet(
                self.request.POST, self.request.FILES, instance=self.object)
        else:
            query_set = ApplicantPrevEducation.objects.select_related('applicant').filter(
                applicant=self.object)
            print(query_set)
            context['preveducation'] = ApplicantPrevEducationFormSet(
                instance=self.object)

        context['title'] = 'Update Applicant Profile'
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        preveducation = context['preveducation']
        with transaction.atomic():
            if preveducation.is_valid():
                form.save()
                preveducation.instance = self.object
                preveducation.save()
                return redirect('applicant:applicant_profile')
            else:
                return self.render_to_response(self.get_context_data(form=form))


class DeleteApplicantProfileView(SuccessMessageMixin, ActiveApplicantRequiredMixin, generic.edit.DeleteView):
    model = ApplicantProfile
    template_name = 'applicant/applicant/delete_applicant_profile.html'
    success_message = "Applicant Profile was deleted successfully"
    success_url = reverse_lazy('applicant:applicant_profile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete Profile'
        return context

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteApplicantProfileView, self).delete(request, *args, **kwargs)


class ApplicationStatusView(ActiveApplicantRequiredMixin, generic.edit.DeleteView):
    def get(self, request, *args, **kwargs):
        applicant_id = kwargs.get('applicant_id')
        applicant_obj = get_object_or_404(ApplicantProfile, id=applicant_id)
        application_obj = list(
            Application.objects.filter(applicant=applicant_obj))

        data = serializers.serialize('json', application_obj)
        return HttpResponse(data, content_type='application/json')


class ApplicantAdmitCardView(ActiveApplicantRequiredMixin, generic.ListView):
    model = Application
    context_object_name = 'applicant_admit_card'
    template_name = 'applicant/admit_card/admit_card.html'
    paginate_by = 10

    def get_queryset(self):
        qs = Application.objects.select_related('owner', 'applicant', 'institute', 'subject').filter(
            owner=self.request.user, status='1', paid=True).only("applicant__student_name","institute__institute_name","subject__subject_name","level","admit_card","owner__username")
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Admit Card'
        return context

    # def get(self, request, *args, **kwargs):
    #     applicant_admit_card = Application.objects.filter(
    #         owner=request.user, status='1', paid=True)
    #     context = {
    #         'title': 'Admit Card',
    #         'applicant_admit_card': applicant_admit_card
    #     }

    #     return render(request, 'applicant/admit_card/admit_card.html', context)

templates/partials/applicant/_breadcrumb.html
<div class="page-title-box">

    <h4 class="page-title">{{title}}</h4>
    <div class="page-title-right">
        <ol class="breadcrumb p-0 m-0">
            <li class="breadcrumb-item"><a href="{% url 'accounts:applicant_dashboard' %}">Dashboard</a></li>
            <li class="breadcrumb-item active">{{title}}</li>
        </ol>
    </div>
    <div class="clearfix"></div>
</div>

templates/partials/applicant/_css.html
{% load static %}


<link href="{% static 'libs/datatables/dataTables.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'libs/datatables/buttons.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'libs/datatables/responsive.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'libs/datatables/select.bootstrap4.min.css' %}" rel="stylesheet" type="text/css" />


<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet" type="text/css" id="bootstrap-stylesheet" />
<link href="{% static 'css/icons.min.css' %}" rel="stylesheet" type="text/css" />
<link href="{% static 'css/app.min.css' %}" rel="stylesheet" type="text/css" id="app-stylesheet" />

<link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css" id="app-stylesheet" />

templates/partials/applicant/_footer.html
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-12">
                {% now 'Y' %} &copy; vortiBD.com app by <a target="_blank" href="https://github.com/MahmudulHassan5809/">Mahmudul Hassan</a>
            </div>
        </div>
    </div>
</footer>

templates/partials/applicant/_js.html
        {% load static %}
        <!-- Vendor js -->
        <script src="{% static 'js/vendor.min.js' %} "></script>
        <!-- App js -->
        <script src="{% static 'js/app.min.js' %} "></script>

        <script src="{% static 'libs/datatables/jquery.dataTables.min.js' %}"></script>
        <script src="{% static 'libs/datatables/dataTables.bootstrap4.min.js' %}"></script>
        <script src="{% static 'libs/datatables/dataTables.buttons.min.js' %}"></script>
        <script src="{% static 'libs/datatables/buttons.bootstrap4.min.js' %}"></script>
        <script src="{% static 'libs/datatables/buttons.html5.min.js' %}"></script>
        <script src="{% static 'libs/datatables/buttons.print.min.js' %}"></script>
        <script src="{% static 'libs/datatables/dataTables.responsive.min.js' %}"></script>
        <script src="{% static 'libs/datatables/responsive.bootstrap4.min.js' %}"></script>
        <script src="{% static 'js/pages/datatables.init.js' %}"></script>

        <!--Start of Tawk.to Script-->
                <script type="text/javascript">
                var Tawk_API=Tawk_API||{}, Tawk_LoadStart=new Date();
                (function(){
                var s1=document.createElement("script"),s0=document.getElementsByTagName("script")[0];
                s1.async=true;
                s1.src='https://embed.tawk.to/5f0c9ca75b59f94722baa585/default';
                s1.charset='UTF-8';
                s1.setAttribute('crossorigin','*');
                s0.parentNode.insertBefore(s1,s0);
                })();
                </script>
        <!--End of Tawk.to Script-->

        <script src="{% static 'js/main.js' %} "></script>

templates/partials/applicant/_landing_nav.html
<nav class="navbar navbar-expand-lg navbar-mainbg">
    <div class="container">
        <a class="navbar-brand navbar-logo" href="{% url 'home_login' %}">{{site_info.site_name}}</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars text-white"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <div class="hori-selector"><div class="left"></div><div class="right"></div></div>
                <li class="nav-item {% if request.resolver_match.url_name == 'home_login' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'home_login' %}"><i class="fas fa-home"></i>Home</a>
                </li>
                <li class="nav-item {% if request.resolver_match.url_name == 'register' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'accounts:register' %}"><i class="fas fa-user-plus"></i>Registration</a>
                </li>

                <li class="nav-item {% if request.resolver_match.url_name == 'site_faq' %} active {% endif %}">
                    <a class="nav-link" href="{% url 'settings:site_faq' %}"><i class="fas fa-question-circle"></i>FAQ</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="javascript:void(0)"><i class="fas fa-headset"></i></i>HELPLINE:{{site_info.site_phone}}</a>
                </li>

            </ul>
        </div>
    </div>
</nav>

templates/partials/applicant/_sidebar.html
{% load static %}
<div class="left-side-menu">
                <div class="slimscroll-menu">
                    <!--- Sidemenu -->
                    <div id="sidebar-menu">
                        <ul class="metismenu" id="side-menu">
                            <li class="menu-title">Navigation</li>
                            <li>
                                <a href="{% url 'applicant:applicant_profile' %}" class="waves-effect">
                                <i class="far fa-user-circle"></i>
                                    Applicant Profile
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'applications:application_list' %}" class="waves-effect">
                                <i class="fas fa-list-ol"></i>
                                    Application List
                                </a>
                            </li>
                            <li>
                                <a href="{% url 'transaction:applicant_payment_list' %}" class="waves-effect">
                                <i class="fas fa-money-bill-wave-alt"></i>
                                    Payment List
                                </a>
                            </li>

                            <li>
                                <a href="{% url 'applicant:applicant_admit_card' %}" class="waves-effect">
                                <i class="far fa-address-card"></i>
                                    Admit Card
                                </a>
                            </li>
                        </ul>
                    </div>
                    <!-- End Sidebar -->
                    <div class="clearfix"></div>
                </div>
                <!-- Sidebar -left -->
            </div>

templates/partials/applicant/_topbar.html
{% load static %}
<div class="navbar-custom">
    <ul class="list-unstyled topnav-menu float-right mb-0">
        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user mr-0 waves-effect" data-toggle="dropdown" href="#" role="button" aria-haspopup="false" aria-expanded="false">
            <img src="{{user.user_profile.profile_pic.url}}" alt="{{user.username}}" class="rounded-circle">
            <span class="pro-user-name ml-1">
            {{user.username|title}}   <i class="mdi mdi-chevron-down"></i>
            </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right profile-dropdown ">
                <!-- item-->
                <div class="dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome !</h6>
                </div>
                <!-- item-->
                <a href="{% url 'accounts:my_profile' %}" class="dropdown-item notify-item">
                <i class="mdi mdi-account-outline"></i>
                <span>Profile</span>
                </a>

                <!-- item-->
                <a href="{% url 'accounts:change_password' %}" class="dropdown-item notify-item">
                <i class="fas fa-key"></i>
                <span>Change Password</span>
                </a>

                <div class="dropdown-divider"></div>
                <!-- item-->
                <a href="{% url 'accounts:logout' %}" class="dropdown-item notify-item">
                <i class="mdi mdi-logout-variant"></i>
                <span>Logout</span>
                </a>
            </div>
        </li>
    </ul>

    <!-- LOGO -->
    <div class="logo-box">
        <a href="index.html" class="logo text-center logo-light">
            <span class="logo-lg">
                <span class="logo-lg-text-light">VortiBd</span>
            </span>
            <span class="logo-sm">
                <!-- <span class="logo-lg-text-dark">V</span> -->
                <img src="{% static 'images/logo-sm.png' %}" alt="" height="22">
            </span>
        </a>
    </div>
    <!-- LOGO -->

    <ul class="list-unstyled topnav-menu topnav-menu-left m-0">
        <li>
            <button class="button-menu-mobile waves-effect">
            <i class="mdi mdi-menu"></i>
            </button>
        </li>
    </ul>
</div>