accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.urls import reverse_lazy

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('login_success/', views.LoginSuccess.as_view(), name='login_success'),
    path('my-profile/', views.MyProfileView.as_view(), name="my_profile"),
    path('change-password/', views.ChangePasswordView.as_view(),
         name="change_password"),
    path('logout/', auth_views.LogoutView.as_view(template_name='common/logout.html',
                                                  extra_context={
                                                      'title': 'Logout',
                                                  }), name="logout"),


    path('applicant/dashboard/',
         views.ApplicantDashboardView.as_view(), name="applicant_dashboard"),
    path('institution/dashboard/',
         views.InstitutionDashboardView.as_view(), name="institution_dashboard"),

    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

institution/urls.py
from django.urls import path
from . import views


app_name = "institution"

urlpatterns = [
    path('admission-session/',
         views.AdmissionSessionView.as_view(), name="admission_session"),
    path('admission-session/create/',
         views.CreateInstitutionSession.as_view(), name="create_session"),
    path('admission-session/delete/<int:pk>/',
         views.DeleteInstitutionSession.as_view(), name="delete_session"),
    path('admission-session/edit/<int:pk>/',
         views.UpdateInstitutionSession.as_view(), name="update_session"),

    path('institute/view/',
         views.MyInstituteView.as_view(), name="my_institute"),
    path('institute/edit/<int:pk>/',
         views.MyInstituteEditView.as_view(), name="my_institute_edit"),

    path('institute/subject/',
         views.MyInstituteSubjectView.as_view(), name="my_institute_subject"),

    path('institute/subject/add/',
         views.AddMyInstituteSubjectView.as_view(), name="my_institute_subject_add"),
    path('institute/subject/edit/<int:pk>/',
         views.EditMyInstituteSubjectView.as_view(), name="my_institute_subject_edit"),
    path('institute/subject/delete/<int:pk>/',
         views.DeleteMyInstituteSubjectView.as_view(), name="my_institute_subject_delete"),

    path('pending-application/', views.PendingApplicationView.as_view(),
         name='institute_pending_application'),

    path('accepted-application/', views.AcceptedApplicationView.as_view(),
         name='institute_accepted_application'),

    path('applicant-profile/<int:applicant_id>/', views.ApplicantProfileView.as_view(),
         name='applicant_profile'),

    path('applicant-admit-card/<int:application_id>/', views.ApplicantAdmitCardView.as_view(),
         name='admit_card_generate'),



    path('institute/instruction/', views.InstituteInstructionView.as_view(),
         name='institute_instruction'),
    path('institute/instruction/create/', views.CreateInstructionView.as_view(),
         name='create_instruction'),
    path('institute/instruction/edit/<int:pk>/', views.EditInstructionView.as_view(),
         name='edit_instruction'),
    path('institute/instruction/delete/<int:pk>/', views.DeleteInstructionView.as_view(),
         name='delete_instruction'),

    path('institute/instruction/details/<int:institution_id>/', views.InstituteInstructionDetailsView.as_view(),
         name='institute_instruction_details'),



    path('institute/search/', views.InstituteSearchView.as_view(),
         name='institute_search'),

    path('institute/subscribe/<int:institution_id>/',
         views.InstituteSubscribeView.as_view(), name='institute_subscribe')
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import HomeLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('applicant/', include('applicant.urls', namespace='applicant')),
    path('institution/', include('institution.urls', namespace='institution')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('transaction/', include('transaction.urls', namespace='transaction')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', HomeLoginView.as_view(), name="home_login"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False


admin.site.site_header = "VortiBD Admin"
admin.site.site_title = "VortiBD Admin Portal"
admin.site.index_title = "VortiBD to Finder Researcher Portal"

templates/common/home.html
{% extends "landing_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-md-8">
        <h1>{{site_info.site_name}}-এ স্বাগতম</h1>
       <p class="lead text-dark">
           vortibd.com হলো এমন একটি ওয়েবসাইট, যেখানে একজন অভিভাবক শুধুমাত্র একটি অ্যাকাউন্ট তৈরী করে আমাদের রেজিস্টার্ড যেকোন শিক্ষা প্রতিষ্ঠানে তার এক বা একাধিক সন্তানের ভর্তির জন্য আবেদন করতে পারবেন।
       </p>
       <p class="lead text-dark">
           vortibd.com-থেকে সকল শিক্ষা প্রতিষ্ঠানের ভর্তি-বিজ্ঞপ্তি জানা যাবে।
       </p>
       <p class="lead text-dark">
           vortibd.com-এ অ্যাকাউন্ট খুলতে ১ মিনিটেরও কম সময় লাগে। আপনি বিনামূল্যে অ্যাকাউন্ট সাইন আপ করতে পারেন এবং প্রতিবছরই ভর্তি-বিজ্ঞপ্তি চলাকালীন সময়ে সহজেই আপনার সন্তানের ভর্তির আবেদন করতে পারেন।
       </p>
       <p class="lead text-dark">
           vortibd.com কোনো বিশেষ শ্রেণীর শিক্ষা প্রতিষ্ঠানের জন্য বিশেষায়িত নয় – এখানে যেকোন স্কুল/কলেজ/বিশ্ববিদ্যালয়/মাদ্রাসা অনলাইনে ভর্তি কার্যক্রম চালু করার জন্য বিনামূল্যে vortibd.com-এ নিবন্ধন করতে পারবেন। শিক্ষা প্রতিষ্ঠানের নিবন্ধন করার বিষয়ে আমরা সকল প্রকার সহযোগীতা করে থাকি । সাহায্যের জন্য ০১৭৯১৩৫০২৬৮ নম্বরে যোগাযোগ করুন।
       </p>
       <p class="lead text-dark">
           ভর্তির আবেদন ফরমের মূল্য যেকোন মোবাইল ব্যাংকিং, ভিসা/মাস্টার/অ্যামেক্স কার্ড অথবা নির্দিষ্ট ব্যাংকের ইন্টারনেট ব্যাংকিং-এর মাধ্যমে পরিশোধ করা যায়।
       </p>
      </div>
      <div class="col-md-4">
          <div class="card mt-4">
                        <div class="card-header p-4 bg-primary">
                            <h4 class="text-white text-center mb-0 mt-0">Login</h4>
                        </div>
                        <div class="card-body">
                            <form action="{% url 'home_login' %}" method="POST" novalidate class="p-2">
                                {% csrf_token %}

                                {{form|crispy}}

                                <div class="form-group mb-4">
                                    <div class="checkbox checkbox-success">
                                       <a href="{% url 'accounts:password_reset' %}" class="text-muted float-right d-block">Forgot your password?</a>
                                    </div>
                                </div>

                                <div class="form-group row text-center mt-4 mb-4">
                                    <div class="col-12">
                                        <button class="btn btn-md btn-block btn-primary waves-effect waves-light" type="submit">Sign In</button>
                                    </div>
                                </div>

                                <div class="form-group row mb-0">
                                    <div class="col-sm-12 text-center">
                                        <p class="text-muted mb-0">Don't have an account? <a href="{% url 'accounts:register' %}" class="text-dark m-l-5"><b>Sign Up</b></a></p>
                                    </div>
                                </div>
                            </form>

                        </div>
                        <!-- end card-body -->
                    </div>
      </div>

      <div class="card w-100 shadow p-4">
          <div class="col-md-12">
              <form method="GET" action="{% url 'institution:institute_search' %}" novalidate>
                  <div class="form-row">
                      <div class="col-5">
                          {{institute_search_form.city|as_crispy_field}}
                      </div>
                      <div class="col-5">
                          {{institute_search_form.subject|as_crispy_field}}
                      </div>
                      <div class="col-2">
                          <button type="submit" class="btn btn-sm btn-primary btn-block mt-4 py-2">
                            <i class="fas fa-search"></i>
                          </button>
                      </div>
                  </div>
              </form>
          </div>
      </div>
    </div>

    <div class="row">
        <div class="card w-100">
            <div class="col-md-12">
                <h1 style="font-size: 25px;" class="text-center lead text-success font-weight-bold border-bottom">Online Admission Going on</h1>

                <div class="live__scroll">
                    <div class="row text-center">
                        {% for admission in on_going_admission %}
                            <div class="col-3 live__scroll--box">
                                <img src="{{admission.institute.institute_pic.url}}" class="img-fluid" width="150px">
                                <p class="lead text-dark">
                                    <a href="{% url 'institution:institute_instruction_details' admission.institute.id %}">{{admission.institute.institute_name}}</a>
                                </p>
                            </div>
                        {% endfor %}
                    </div>
                </div>


            </div>
        </div>
    </div>

    <div class="row">
        <div class="card w-100">
            <div class="col-md-12">
                <h1 style="font-size: 25px;" class="text-center lead text-success font-weight-bold border-bottom">All Institute</h1>

                <div class="live__scroll">
                    <div class="row text-center">
                        {% for institute in all_institute_profile %}
                            <div class="col-3 live__scroll--box">
                                <img src="{{institute.institute_pic.url}}" class="img-fluid" width="150px">

                                <h3 class="font-weight-bold text-dark text-center">Subscribe Us</h3>
                                <form action="{% url 'institution:institute_subscribe' institute.id %}" method="POST" class="mt-1">
                                  {% csrf_token %}
                                  {{subscription_form|crispy}}

                                  <button type="submit" class="btn btn-info btn-sm btn-block">Subscribe</button>
                                </form>

                            </div>
                        {% endfor %}
                    </div>
                </div>


            </div>
        </div>
    </div>


{% endblock content %}

templates/common/institute_instruction.html
{% extends "landing_base.html" %}

{% load crispy_forms_tags %}


{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <div class="card card-inverse text-white" style="background-color: #0fc846; border-color: #0fc846;">
            <div class="card-body">
                <div class="float-left">
                    <h1 class="card-title text-white" style="font-size:30px;">{{institution_obj.institute_name}}</h1>
                    <p class="card-text m-0">{{institution_obj.institute_location}}</p>
                    <p class="card-text m-0">{{institution_obj.institute_city}}</p>
                    <p class="card-text m-0">Institute Code {{institution_obj.institute_code}}</p>

                    <h5 class="lead text-dark font-weight-bold">Subscribe Us</h5>
                    <form action="{% url 'institution:institute_subscribe' institution_obj.id %}" method="POST" novalidate>
                        {% csrf_token %}
                        {{subscription_form|crispy}}
                    </form>
                </div>
                <div class="float-right">
                    {% if institution_obj.institute_pic %}
                        <img src="{{institution_obj.institute_pic.url}}" width="150px">
                    {% endif %}
                </div>

            </div>
        </div>


        <div class="card card-inverse text-white">
            {% for instruction in institution_instructions %}
                <div class="card-header bg-info">
                    <h1 class="lead font-weight-bold">
                        {{instruction.title}}
                    </h1>
                </div>
                <div class="card-body text-dark">
                    <p class="lead text-dark">
                        {{instruction.body|safe}}
                    </p>
                </div>
            {% endfor %}
        </div>

    </div>
</div>


{% endblock content %}

templates/common/logout.html
{% extends "landing_base.html" %}

{% load static %}


{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="row justify-content-center">
        <div class="col-md-8 col-lg-6 col-xl-6">
            <div class="card mt-4">
                <div class="card-header text-center p-4 bg-primary">
                    <h4 class="text-white mb-0 mt-0">You Have Successfully Logged Out</h4>
                </div>
                <div class="card-body">
                    <p>
                        If You Want To Login Again Click Here<a class="btn btn-outline-info mx-2 btn-sm" href="{% url 'home_login' %}">Sign In</a>now.
                    </p>
                </div>

            </div>

        </div>
    </div>
{% endblock content %}

templates/common/search_results.html
{% extends "landing_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
        <h1>vortibd.com-এ স্বাগতম</h1>
       <p class="lead text-dark">
           vortibd.com হলো এমন একটি ওয়েবসাইট, যেখানে একজন অভিভাবক শুধুমাত্র একটি অ্যাকাউন্ট তৈরী করে আমাদের রেজিস্টার্ড যেকোন শিক্ষা প্রতিষ্ঠানে তার এক বা একাধিক সন্তানের ভর্তির জন্য আবেদন করতে পারবেন।
       </p>
       <p class="lead text-dark">
           vortibd.com-থেকে সকল শিক্ষা প্রতিষ্ঠানের ভর্তি-বিজ্ঞপ্তি জানা যাবে।
       </p>
       <p class="lead text-dark">
           vortibd.com-এ অ্যাকাউন্ট খুলতে ১ মিনিটেরও কম সময় লাগে। আপনি বিনামূল্যে অ্যাকাউন্ট সাইন আপ করতে পারেন এবং প্রতিবছরই ভর্তি-বিজ্ঞপ্তি চলাকালীন সময়ে সহজেই আপনার সন্তানের ভর্তির আবেদন করতে পারেন।
       </p>
       <p class="lead text-dark">
           vortibd.com কোনো বিশেষ শ্রেণীর শিক্ষা প্রতিষ্ঠানের জন্য বিশেষায়িত নয় – এখানে যেকোন স্কুল/কলেজ/বিশ্ববিদ্যালয়/মাদ্রাসা অনলাইনে ভর্তি কার্যক্রম চালু করার জন্য বিনামূল্যে vortibd.com-এ নিবন্ধন করতে পারবেন। শিক্ষা প্রতিষ্ঠানের নিবন্ধন করার বিষয়ে আমরা সকল প্রকার সহযোগীতা করে থাকি । সাহায্যের জন্য ০১৭৯১৩৫০২৬৮ নম্বরে যোগাযোগ করুন।
       </p>
       <p class="lead text-dark">
           ভর্তির আবেদন ফরমের মূল্য যেকোন মোবাইল ব্যাংকিং, ভিসা/মাস্টার/অ্যামেক্স কার্ড অথবা নির্দিষ্ট ব্যাংকের ইন্টারনেট ব্যাংকিং-এর মাধ্যমে পরিশোধ করা যায়।
       </p>
      </div>


      <div class="card w-100 shadow p-4">
          <div class="col-md-12">
              <form method="GET" action="{% url 'institution:institute_search' %}" novalidate>
                  <div class="form-row">
                      <div class="col-5">
                          {{institute_search_form.city|as_crispy_field}}
                      </div>
                      <div class="col-5">
                          {{institute_search_form.subject|as_crispy_field}}
                      </div>
                      <div class="col-2">
                          <button type="submit" class="btn btn-sm btn-primary btn-block mt-4 py-2">
                            <i class="fas fa-search"></i>
                          </button>
                      </div>
                  </div>
              </form>
          </div>
      </div>
    </div>

    <div class="row">
        <div class="card w-100">
            <div class="col-md-12">
                <h1 style="font-size: 25px;" class="text-center lead text-success font-weight-bold border-bottom">{{title}}</h1>

                <div class="live__scroll">
                    <div class="row text-center">
                        {% for institute in institute_list %}
                            <div class="col-3 live__scroll--box">
                                {% if institute.institute_pic %}
                                  <img src="{{institute.institute_pic.url}}" class="img-fluid" width="150px">
                                {% endif %}
                                <p class="lead text-dark">
                                    <a href="{% url 'institution:institute_instruction_details' institute.id %}">{{institute.institute_name}}</a>
                                </p>
                            </div>
                        {% endfor %}
                    </div>
                </div>


            </div>
        </div>
    </div>


{% endblock content %}

templates/common/site_faq.html
{% extends "landing_base.html" %}



{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h1 class="lead text-dark font-weight-bold text-center" style="font-size: 30px;">
            {{title}}
        </h1>
        <hr>

        <div id="accordion" class="mb-3">
            {% for faq in faq_list %}
                <div class="card mb-0">
                <div class="card-header" id="heading{{faq.id}}">
                    <h6 class="m-0">
                        <a href="#collapse{{faq.id}}" class="text-dark font-weight-bold" data-toggle="collapse"
                                aria-expanded="true"
                                aria-controls="collapse{{faq.id}}">
                            {{faq.question}}
                        </a>
                    </h6>
                </div>

                <div id="collapse{{faq.id}}" class="collapse {% if forloop.counter == 1 %}show{% endif %}" aria-labelledby="heading{{faq.id}}" data-parent="#accordion">
                    <div class="card-body text-dark font-weight-bold">
                        {{faq.answer}}
                    </div>
                </div>
                </div>
            {% endfor %}
        </div>

    </div>
</div>


{% endblock content %}