accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.urls import reverse_lazy

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('login_success/', views.LoginSuccess.as_view(), name='login_success'),
    path('my-profile/', views.MyProfileView.as_view(), name="my_profile"),
    path('change-password/', views.ChangePasswordView.as_view(),
         name="change_password"),
    path('logout/', auth_views.LogoutView.as_view(template_name='common/logout.html',
                                                  extra_context={
                                                      'title': 'Logout',
                                                  }), name="logout"),


    path('applicant/dashboard/',
         views.ApplicantDashboardView.as_view(), name="applicant_dashboard"),
    path('institution/dashboard/',
         views.InstitutionDashboardView.as_view(), name="institution_dashboard"),

    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

applicant/urls.py
from django.urls import path
from . import views


app_name = "applicant"

urlpatterns = [
    path('profile/', views.ApplicantProfileView.as_view(),
         name="applicant_profile"),
    path('create/profile/', views.CreateApplicantProfileView.as_view(),
         name="create_applicant_profile"),
    path('edit/profile/<int:pk>/', views.EditApplicantProfileView.as_view(),
         name="edit_applicant_profile"),
    path('delete/profile/<int:pk>/', views.DeleteApplicantProfileView.as_view(),
         name="delete_applicant_profile"),

    path('application/status/<int:applicant_id>/', views.ApplicationStatusView.as_view(),
         name="application_status"),

    path('application/admit/card/', views.ApplicantAdmitCardView.as_view(),
         name="applicant_admit_card"),
]

applications/urls.py
from django.urls import path
from . import views


app_name = "applications"

urlpatterns = [
    path('apply/<int:applicant_id>/', views.ApplyApplicationView.as_view(),
         name="apply"),

    path('application/list/', views.ApplicationListView.as_view(),
         name="application_list"),

    path('application/delete/<int:pk>/', views.DeleteApplicationView.as_view(),
         name="application_delete"),

    path('ajax/load-subjects/', views.load_subjects, name='ajax_load_subjects'),







]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import HomeLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('applicant/', include('applicant.urls', namespace='applicant')),
    path('institution/', include('institution.urls', namespace='institution')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('transaction/', include('transaction.urls', namespace='transaction')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', HomeLoginView.as_view(), name="home_login"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False


admin.site.site_header = "VortiBD Admin"
admin.site.site_title = "VortiBD Admin Portal"
admin.site.index_title = "VortiBD to Finder Researcher Portal"

applicant/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.dispatch import receiver
from django.db.models.signals import post_save
# Create your models here.


class ApplicantProfile(models.Model):
    GENDER_CHOICES = (
        ('1', 'Male'),
        ('2', 'Female'),
    )
    RELIGION_CHOICES = (
        ('Islam', 'Islam'),
        ('Hinduism', 'Hinduism'),
        ('Cristian', 'Cristian'),
        ('Buddhist', 'Buddhist'),
    )
    FREEDOM_FIGHTER_CHOICES = (
        ('No', 'No'),
        ('Yes', 'Yes'),
    )
    IS_AUTISM_CHOICES = (
        ('No', 'No'),
        ('Yes', 'Yes'),
    )
    owner = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE, related_name='user_applications')
    student_name = models.CharField(max_length=250)
    father_name = models.CharField(max_length=250)
    father_occupation = models.CharField(max_length=250)
    mother_name = models.CharField(max_length=250)
    mother_occupation = models.CharField(max_length=250)
    present_address = models.TextField()
    permanent_address = models.TextField()
    contact_number = models.CharField(max_length=20)
    email_address = models.EmailField(max_length=254, null=True, blank=True)
    birth_date = models.CharField(max_length=230)
    birth_id = models.CharField(max_length=250, null=True, blank=True)
    gender = models.CharField(max_length=10, choices=GENDER_CHOICES)
    religion = models.CharField(max_length=10, choices=RELIGION_CHOICES)
    blood_group = models.CharField(max_length=20)
    freedom_fighter_quota = models.CharField(
        max_length=150, choices=FREEDOM_FIGHTER_CHOICES, default="0")
    is_autism = models.CharField(
        max_length=150, choices=IS_AUTISM_CHOICES, default="0")
    height = models.FloatField(null=True, blank=True)
    local_guardian_name = models.CharField(
        max_length=250, null=True, blank=True)
    relation_with_applicant = models.CharField(
        max_length=255, null=True, blank=True)
    guardian_income = models.FloatField()
    student_pic = models.ImageField(upload_to="student")

    class Meta:
        verbose_name = 'Applicant Form'
        verbose_name_plural = '1. Applicant Form'

    def __str__(self):
        return self.student_name


class ApplicantPrevEducation(models.Model):
    BOARD_CHOICES = (
        ('Dhaka', 'Dhaka'),
        ('Khulna', 'Khulna'),
        ('Rajshahi', 'Rajshahi'),
        ('Rajshahi', 'Rajshahi'),
        ('Jessore', 'Jessore'),
        ('Comilla', 'Comilla'),
    )
    EXAM_CHOICES = (
        ('SSC', 'SSC'),
        ('HSC', 'HSC')
    )
    applicant = models.ForeignKey(
        ApplicantProfile, on_delete=models.CASCADE, related_name='applicant_pre_edu')
    exam_name = models.CharField(max_length=10, choices=EXAM_CHOICES)
    board_name = models.CharField(max_length=10, choices=BOARD_CHOICES)
    institute_name = models.CharField(max_length=255)
    passing_year = models.IntegerField()
    result = models.FloatField()

    def __str__(self):
        return self.applicant.student_name



@receiver(post_save, sender=ApplicantProfile)
def create_profile(sender, instance, created, **kwargs):
    print('signal','-----',sender)
    

applicant/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from .models import ApplicantPrevEducation, ApplicantProfile


class DateInput(forms.DateInput):
    input_type = 'date'


class ApplicantProfileForm(ModelForm):
    present_address = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))
    permanent_address = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))

    class Meta:
        model = ApplicantProfile
        exclude = ('owner',)
        widgets = {
            'birth_date': DateInput(),
        }


class ApplicantPrevEducationForm(ModelForm):
    class Meta:
        model = ApplicantPrevEducation
        fields = '__all__'


ApplicantPrevEducationFormSet = inlineformset_factory(
    ApplicantProfile, ApplicantPrevEducation, form=ApplicantPrevEducationForm, extra=1)

applicant/views.py
from django.shortcuts import redirect, get_object_or_404, HttpResponse
from django.urls import reverse_lazy
from django.db import transaction
from accounts.mixins import ActiveApplicantRequiredMixin
from django.contrib import messages
from django.core import serializers
from django.contrib.messages.views import SuccessMessageMixin
from applications.models import Application
from .forms import ApplicantPrevEducationFormSet, ApplicantProfileForm
from .models import ApplicantPrevEducation, ApplicantProfile
from django.views import generic
# Create your views here.


class ApplicantProfileView(generic.ListView):
    model = ApplicantProfile
    context_object_name = 'all_applicant_profile'
    template_name = 'applicant/applicant/all_applicant_profile.html'

    def get_queryset(self):
        qs = ApplicantProfile.objects.select_related(
            'owner').filter(owner=self.request.user).only("owner__username", "father_name", "mother_name", "student_name", "student_pic")
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Applicant Profile'
        return context


class CreateApplicantProfileView(SuccessMessageMixin, ActiveApplicantRequiredMixin, generic.CreateView):
    model = ApplicantProfile
    form_class = ApplicantProfileForm
    template_name = 'applicant/applicant/create_applicant_profile.html'
    success_message = "Applicant Profile was created successfully"
    success_url = reverse_lazy('applicant:applicant_profile')

    def get_context_data(self, **kwargs):
        context = super(CreateApplicantProfileView,
                        self).get_context_data(**kwargs)
        if self.request.POST:
            context['preveducation'] = ApplicantPrevEducationFormSet(
                self.request.POST, self.request.FILES)
        else:
            context['preveducation'] = ApplicantPrevEducationFormSet()
        context['title'] = 'Create Applicant Profile'
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        preveducation = context['preveducation']
        with transaction.atomic():
            if preveducation.is_valid():
                self.object = form.save(commit=False)
                self.object.owner = self.request.user
                self.object.save()
                preveducation.instance = self.object
                preveducation.save()
                return redirect('applicant:applicant_profile')
            else:
                return self.render_to_response(self.get_context_data(form=form))

class EditApplicantProfileView(SuccessMessageMixin, ActiveApplicantRequiredMixin, generic.UpdateView):
    model = ApplicantProfile
    context_object_name = 'applicant_profile'
    form_class = ApplicantProfileForm
    success_message = "Applicant Profile was updated successfully"
    template_name = 'applicant/applicant/update_applicant_profile.html'
    success_url = reverse_lazy('applicant:applicant_profile')

    def get_context_data(self, **kwargs):
        context = super(EditApplicantProfileView,
                        self).get_context_data(**kwargs)
        if self.request.POST:
            context['preveducation'] = ApplicantPrevEducationFormSet(
                self.request.POST, self.request.FILES, instance=self.object)
        else:
            query_set = ApplicantPrevEducation.objects.select_related('applicant').filter(
                applicant=self.object)
            print(query_set)
            context['preveducation'] = ApplicantPrevEducationFormSet(
                instance=self.object)

        context['title'] = 'Update Applicant Profile'
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        preveducation = context['preveducation']
        with transaction.atomic():
            if preveducation.is_valid():
                form.save()
                preveducation.instance = self.object
                preveducation.save()
                return redirect('applicant:applicant_profile')
            else:
                return self.render_to_response(self.get_context_data(form=form))


class DeleteApplicantProfileView(SuccessMessageMixin, ActiveApplicantRequiredMixin, generic.edit.DeleteView):
    model = ApplicantProfile
    template_name = 'applicant/applicant/delete_applicant_profile.html'
    success_message = "Applicant Profile was deleted successfully"
    success_url = reverse_lazy('applicant:applicant_profile')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Delete Profile'
        return context

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, self.success_message)
        return super(DeleteApplicantProfileView, self).delete(request, *args, **kwargs)


class ApplicationStatusView(ActiveApplicantRequiredMixin, generic.edit.DeleteView):
    def get(self, request, *args, **kwargs):
        applicant_id = kwargs.get('applicant_id')
        applicant_obj = get_object_or_404(ApplicantProfile, id=applicant_id)
        application_obj = list(
            Application.objects.filter(applicant=applicant_obj))

        data = serializers.serialize('json', application_obj)
        return HttpResponse(data, content_type='application/json')


class ApplicantAdmitCardView(ActiveApplicantRequiredMixin, generic.ListView):
    model = Application
    context_object_name = 'applicant_admit_card'
    template_name = 'applicant/admit_card/admit_card.html'
    paginate_by = 10

    def get_queryset(self):
        qs = Application.objects.select_related('owner', 'applicant', 'institute', 'subject').filter(
            owner=self.request.user, status='1', paid=True).only("applicant__student_name","institute__institute_name","subject__subject_name","level","admit_card","owner__username")
        return qs

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Admit Card'
        return context

    # def get(self, request, *args, **kwargs):
    #     applicant_admit_card = Application.objects.filter(
    #         owner=request.user, status='1', paid=True)
    #     context = {
    #         'title': 'Admit Card',
    #         'applicant_admit_card': applicant_admit_card
    #     }

    #     return render(request, 'applicant/admit_card/admit_card.html', context)

templates/applicant/applicant/all_applicant_profile.html
{% extends "applicant_base.html" %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4 class="float-left">
                        Applicant Profile(s)
                    </h4>
                    <a href="{% url 'applicant:create_applicant_profile' %}" class="float-right btn btn-sm btn-info">
                        <i class="fas fa-plus">Add Another Profile</i>
                    </a>
                </div>
                <div class="card-body">
                    <table class="table table-striped table-inverse table-hover">
                        <thead>
                            <tr>
                                <th>Srl</th>
                                <th>Photo</th>
                                <th>Name</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for profile in all_applicant_profile %}


                            <tr>
                                <td>
                                    {{forloop.counter}}
                                </td>
                                <td>
                                    <img src="{{profile.student_pic.url}}" width="120px">
                                </td>
                                <td>
                                    {{profile.student_name}}<br>
                                    {{profile.father_name}}<br>
                                    {{profile.mother_name}}<br>
                                </td>
                                <td>
                                    <a type="button" data-toggle="modal" data-target="#applicationStatusModel" class="btn-block btn btn-info btn-sm text-white status" data-status-url="{% url 'applicant:application_status' profile.id %}">
                                        <i class="fas fa-redo mr-1"></i> Application Status
                                    </a>
                                    <a href="{% url 'applications:apply' profile.id %}" class="btn-block btn btn-primary btn-sm">
                                        <i class="far fa-paper-plane mr-1"></i> Apply Now
                                    </a>
                                    <a href="{% url 'applicant:edit_applicant_profile' profile.id %}" class="btn-block btn btn-success btn-sm">
                                        <i class="fas fa-edit mr-1"></i> Edit Profile
                                    </a>
                                    <a href="{% url 'applicant:delete_applicant_profile' profile.id %}" class="btn-block btn btn-danger btn-sm">
                                        <i class="fas fa-trash mr-1"></i> Delete Profile
                                    </a>
                                </td>
                            </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>


<div class="modal fade" id="applicationStatusModel" tabindex="-1" role="dialog" aria-labelledby="applicationModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="applicationModalLabel">Application Status</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                  <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>
{% endblock content %}



{% block script %}
    <script>
        jQuery(document).ready(function($) {
            $(document.body).on('click', '.status', function(event) {
                event.preventDefault();
                let statusHtml = '';
                url = $(this).attr("data-status-url");
                $.ajax({
                    url: url,
                    success: function (data) {
                        let status = '';
                        let admit_card = false;
                        data.forEach( function(element, index) {
                            if (element.fields.status == '0'){
                               status = 'Pending'
                            }else if(element.fields.status == '1'){
                                status = 'Accepted'
                                admit_card = true;
                            }else{
                                status = 'Canceled'
                            }
                            statusHtml += `
                                <div class="card">
                                    <ul class="list-group list-group-flush font-weight-bold text-dark">
                                        <li class="list-group-item">Application Fee : ${element.fields.paid ? 'Paid' : 'Pending'}</li>
                                        <li class="list-group-item">Status : ${status}</li>
                                        <li class="list-group-item">
                                            Admit Card
                                            <a href="/media/${element.fields.admit_card}">Download</a>
                                        </li>
                                    </ul>
                                </div>
                            `
                            console.log(element.fields)
                        });
                        $('.modal-body').append(statusHtml);
                    },
                    error: function (xhr, ajaxOptions, thrownError) {
                       console.log(xhr)
                    }
                });
            });

            $(".modal").on("hidden.bs.modal", function(){
                $(".modal-body").html("");
            });
        });
    </script>
{% endblock script %}

templates/applicant/applicant/create_applicant_profile.html
{% extends "applicant_base.html" %}
{% load static %}

{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-8 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h4 class="text-center">
                        Create Applicant Profile (* চিহ্নিত ফিল্ড গুলো অবশ্যই পূরণীয় )
                    </h4>
                </div>
                <div class="card-body">
                    <form action="{% url 'applicant:create_applicant_profile' %}" method="post" novalidate enctype="multipart/form-data">{% csrf_token %}
                        {{ form.student_name|as_crispy_field }}
                        {{ form.father_name|as_crispy_field }}
                        <div class="form-row">
                           <div class="col-6">
                               {{ form.father_occupation|as_crispy_field }}
                           </div>
                           <div class="col-6">
                               {{ form.guardian_income|as_crispy_field }}
                           </div>
                        </div>
                        {{ form.mother_name|as_crispy_field }}
                        {{ form.mother_occupation|as_crispy_field }}
                        {{ form.present_address|as_crispy_field }}
                        {{ form.permanent_address|as_crispy_field }}

                        <div class="form-row">
                           <div class="col-6">
                               {{ form.contact_number|as_crispy_field }}
                           </div>
                           <div class="col-6">
                               {{ form.email_address|as_crispy_field }}
                           </div>
                        </div>

                        <div class="form-row">
                           <div class="col-6">
                               {{ form.birth_date|as_crispy_field }}
                           </div>
                           <div class="col-6">
                               {{ form.birth_id|as_crispy_field }}
                           </div>
                        </div>

                        <div class="form-row">
                           <div class="col-6">
                               {{ form.gender|as_crispy_field }}
                           </div>
                           <div class="col-6">
                               {{ form.height|as_crispy_field }}
                           </div>
                        </div>

                        <div class="form-row">
                           <div class="col-6">
                               {{ form.religion|as_crispy_field }}
                           </div>
                           <div class="col-6">
                               {{ form.blood_group|as_crispy_field }}
                           </div>
                        </div>

                        <div class="form-row">
                           <div class="col-6">
                               {{ form.freedom_fighter_quota|as_crispy_field }}
                           </div>
                           <div class="col-6">
                               {{ form.is_autism|as_crispy_field }}
                           </div>
                        </div>

                        <div class="form-row">
                           <div class="col-6">
                               {{ form.local_guardian_name|as_crispy_field }}
                           </div>
                           <div class="col-6">
                               {{ form.relation_with_applicant|as_crispy_field }}
                           </div>
                        </div>

                        {{ form.student_pic|as_crispy_field }}

                        <hr>
                        <h5 class="lead text-dark">Add Previous Education History</h5>
                        <hr>
                        <table class="table">
                            {{ preveducation.management_form }}

                            {% for form in preveducation.forms %}
                                {% if forloop.first %}
                                    <thead>
                                    <tr>
                                        {% for field in form.visible_fields %}
                                            <th>{{ field.label|capfirst }}</th>
                                        {% endfor %}
                                    </tr>
                                    </thead>
                                {% endif %}
                                <tr class="{% cycle "row1" "row2" %} formset_row">
                                    {% for field in form.visible_fields %}
                                        <td>
                                            {# Include the hidden fields in the form #}
                                            {% if forloop.first %}
                                                {% for hidden in form.hidden_fields %}
                                                    {{ hidden }}
                                                {% endfor %}
                                            {% endif %}
                                            {{ field.errors.as_ul }}
                                            {{ field|as_crispy_field }}
                                        </td>
                                    {% endfor %}
                                </tr>
                            {% endfor %}
                        </table>
                        <input type="submit" value="Save"/>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}


{% block script %}
    <script src="{% static 'js/jquery.formset.js' %}"></script>
    <script type="text/javascript">
        $('.formset_row').formset({
            addText: 'Add Education',
            deleteText: 'remove',
            prefix: 'preveducation_set'
        });
    </script>
{% endblock script %}

templates/applicant/applicant/delete_applicant_profile.html
{% extends "applicant_base.html" %}

{% block title %}
    {{title}}
{% endblock title %}


{% block content %}
    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3 class="lead text-dark">Delete profile</h3>
                </div>
                <div class="card-body">
                    <form method="post">{% csrf_token %}
                        <p>Are you sure you want to delete "{{ object }}'s Profile"?</p>
                        <input type="submit" value="Confirm" class="btn btn-danger">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}