accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

from django.urls import reverse_lazy

app_name = "accounts"
urlpatterns = [
    path('register/', views.RegisterView.as_view(), name="register"),
    path('activate/<uidb64>/<token>', views.activate, name='activate'),
    path('login_success/', views.LoginSuccess.as_view(), name='login_success'),
    path('my-profile/', views.MyProfileView.as_view(), name="my_profile"),
    path('change-password/', views.ChangePasswordView.as_view(),
         name="change_password"),
    path('logout/', auth_views.LogoutView.as_view(template_name='common/logout.html',
                                                  extra_context={
                                                      'title': 'Logout',
                                                  }), name="logout"),


    path('applicant/dashboard/',
         views.ApplicantDashboardView.as_view(), name="applicant_dashboard"),
    path('institution/dashboard/',
         views.InstitutionDashboardView.as_view(), name="institution_dashboard"),

    path('password_reset/', auth_views.PasswordResetView.as_view(success_url=reverse_lazy('accounts:password_reset_done')),
         name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>',
         auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(),
         name='password_reset_complete'),

]

applicant/urls.py
from django.urls import path
from . import views


app_name = "applicant"

urlpatterns = [
    path('profile/', views.ApplicantProfileView.as_view(),
         name="applicant_profile"),
    path('create/profile/', views.CreateApplicantProfileView.as_view(),
         name="create_applicant_profile"),
    path('edit/profile/<int:pk>/', views.EditApplicantProfileView.as_view(),
         name="edit_applicant_profile"),
    path('delete/profile/<int:pk>/', views.DeleteApplicantProfileView.as_view(),
         name="delete_applicant_profile"),

    path('application/status/<int:applicant_id>/', views.ApplicationStatusView.as_view(),
         name="application_status"),

    path('application/admit/card/', views.ApplicantAdmitCardView.as_view(),
         name="applicant_admit_card"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

from accounts.views import HomeLoginView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('applicant/', include('applicant.urls', namespace='applicant')),
    path('institution/', include('institution.urls', namespace='institution')),
    path('applications/', include('applications.urls', namespace='applications')),
    path('transaction/', include('transaction.urls', namespace='transaction')),
    path('settings/', include('settings.urls', namespace='settings')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('', HomeLoginView.as_view(), name="home_login"),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.FORCE_STATIC_FILE_SERVING and not settings.DEBUG:
    settings.DEBUG = True
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    settings.DEBUG = False


admin.site.site_header = "VortiBD Admin"
admin.site.site_title = "VortiBD Admin Portal"
admin.site.index_title = "VortiBD to Finder Researcher Portal"

transaction/urls.py
from django.urls import path
from . import views


app_name = "transaction"

urlpatterns = [
    path('transaction-method/',
         views.TransactionMethodView.as_view(), name="transaction_method"),
    path('transaction-method/add/',
         views.AddTransactionMethodView.as_view(), name="add_transaction_method"),
    path('transaction-method/edit/<int:pk>/',
         views.EditTransactionMethodView.as_view(), name="edit_transaction_method"),

    path('transaction-method/delete/<int:pk>/',
         views.DeleteTransactionMethodView.as_view(), name="delete_transaction_method"),

    path('application/pay-fee/<int:application_id>/<int:institute_id>/', views.PayApplicationFeeView.as_view(),
         name="pay_application_fee"),

    path('applicant/payment-list/', views.ApplicantPaymentListView.as_view(),
         name="applicant_payment_list"),

    path('institute/payment-list/', views.InstitutePaymentListView.as_view(),
         name="institute_payment_list"),

    path('institute/payment/check/<int:id>/', views.InstitutePaymentCheckView.as_view(),
         name="institute_payment_check"),


    path('applicant/transaction/details/<int:transaction_id>/',
         views.TransactionDetailsView.as_view(), name='transaction_details')
]

institution/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from ckeditor.fields import RichTextField
from institution.tasks import set_admission_as_inactive, send_email_to_subscriber
# Create your models here.


class InstitutionProfile(models.Model):
    GENDER_CHOICES = (
        ('1', 'Male'),
        ('2', 'Female'),
        ('3', 'Both'),
    )
    user = models.OneToOneField(
        get_user_model(), on_delete=models.CASCADE, related_name='user_institute')
    institute_name = models.CharField(max_length=255, default='Institute Name')
    institute_city = models.CharField(max_length=150, default='Institute City')
    institute_location = models.CharField(
        max_length=255, default='Institute Location')
    institute_code = models.CharField(max_length=50, default='Institute Code')
    application_fee = models.FloatField(default=0.0)
    gender = models.CharField(
        max_length=10, choices=GENDER_CHOICES, default='3')
    institute_pic = models.ImageField(
        upload_to="institution", blank=True, null=True)
    active = models.BooleanField(default=True)

    class Meta:
        verbose_name = 'InstitutionProfile'
        verbose_name_plural = '1. InstitutionProfile'

    def __str__(self):
        return self.institute_name


class InstitutionSubject(models.Model):
    LEVEL_CHOICES = (
        ('1', 'Bachelor'),
        ('2', 'Masters'),
        ('3', 'Both'),
    )
    institute = models.ForeignKey(
        InstitutionProfile, on_delete=models.CASCADE, related_name='institute_subjects')
    subject_name = models.CharField(max_length=250)
    level = models.CharField(
        max_length=10, choices=LEVEL_CHOICES)
    active = models.BooleanField(default=True)

    def __init__(self, *args, **kwargs):
        super().__init__(args, kwargs)
        self.institute_subjects = None

    def __str__(self):
        return self.subject_name


# class SingleInstanceMixin(object):
#     """Makes sure that no more than one instance of a given model is created."""

#     def clean(self):
#         model = self.__class__
#         if (model.objects.count() > 0 and self.id != model.objects.get().id):
#             raise ValidationError(
#                 "Can only create 1 %s instance Please Edit The Previous One" % model.__name__)
#         super(SingleInstanceMixin, self).clean()


class AdmissionSession(models.Model):
    LEVEL_CHOICES = (
        ('1', 'Bachelor'),
        ('2', 'Masters'),
        ('3', 'Bachelor & Masters')
    )
    institute = models.OneToOneField(
        InstitutionProfile, on_delete=models.CASCADE, related_name='institute_session')
    session_name = models.CharField(max_length=200)
    year = models.IntegerField()
    level = models.CharField(max_length=50, choices=LEVEL_CHOICES, default='3')
    end_time = models.DateTimeField(null=True, blank=True)
    status = models.BooleanField()

    class Meta:
        verbose_name = 'AdmissionSession'
        verbose_name_plural = '2. AdmissionSession'

    def save(self, *args, **kwargs):
        create_task = False
        if self.pk is None:
            create_task = True

        super(AdmissionSession, self).save(*args, **kwargs)

        if create_task and self.end_time:
            set_admission_as_inactive.apply_async(args=[self.id], eta=self.end_time)

    def __str__(self):
        return self.session_name


class InstituteInstruction(models.Model):
    institute = models.ForeignKey(
        InstitutionProfile, on_delete=models.CASCADE, related_name='institute_instructions')
    title = models.CharField(max_length=255)
    body = RichTextField()

    class Meta:
        verbose_name = 'InstituteInstruction'
        verbose_name_plural = '3. InstituteInstruction'

    def __str__(self):
        return self.title


class Subscription(models.Model):
    institute = models.ForeignKey(
        InstitutionProfile, on_delete=models.CASCADE, related_name='institute_subscribers')
    user_email = models.EmailField()

    def __str__(self):
        return f"{self.user_email} subscribes {self.institute.institute_name}"


@receiver(post_save, sender=AdmissionSession)
def send_admission_start_msg(sender, instance, created, **kwargs):
    post_save.disconnect(send_admission_start_msg, sender=sender)

    if instance.status:
        if created:
            send_email_to_subscriber.delay(list(
                instance.institute.institute_subscribers.all().values_list('user_email', flat=True)), instance.institute.institute_name)
        else:
            send_email_to_subscriber.delay(list(
                instance.institute.institute_subscribers.all().values_list('user_email', flat=True)), instance.institute.institute_name)

    post_save.connect(send_admission_start_msg, sender=sender)

transaction/models.py
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.contrib.auth import get_user_model
from applications.models import Application
from institution.models import InstitutionProfile


class InstitutionTransactionMethod(models.Model):
    institute = models.ForeignKey(
        InstitutionProfile, on_delete=models.CASCADE, related_name='institute_transaction')
    method_name = models.CharField(max_length=50)
    reference_id = models.CharField(max_length=50)
    counter_no = models.IntegerField()
    account_number = models.CharField(max_length=50)
    instruction = models.TextField()

    class Meta:
        verbose_name = 'Institution Transaction'
        verbose_name_plural = '1. Institution Transaction'

    def __str__(self):
        return f"{self.method_name} -- {self.account_number}"


class ApplicationPayment(models.Model):
    STATUS_CHOICES = (
        ('0', 'Pending'),
        ('1', 'Completed'),
        ('2', 'Canceled')
    )
    application = models.ForeignKey(
        Application, on_delete=models.CASCADE)
    owner = models.ForeignKey(
        get_user_model(), on_delete=models.CASCADE)
    institute = models.ForeignKey(
        InstitutionProfile, on_delete=models.CASCADE)
    payment_method = models.ForeignKey(
        InstitutionTransactionMethod, on_delete=models.CASCADE)
    send_from = models.CharField(max_length=20)
    transaction_number = models.CharField(max_length=50)
    status = models.CharField(
        max_length=10, choices=STATUS_CHOICES, default='0')
    completed = models.BooleanField(default=False)
    pending = models.BooleanField(default=True)
    cancel = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True, auto_now=False)

    class Meta:
        verbose_name = 'ApplicationPayment'
        verbose_name_plural = '2. ApplicationPayment'

    def __str__(self):
        return self.payment_method.method_name


# Payment
@receiver(post_save, sender=ApplicationPayment)
def applicant_payment(instance, created):
    if not instance.completed:
        if created and instance.application.status == '3':
            instance.application.status = '0'
            instance.application.save()
        if instance.status == "0" and not instance.pending:
            instance.pending = True
            instance.application.status = '0'
            instance.save()
            instance.application.save()
        if instance.status == "2" and not instance.cancel:
            instance.cancel = True
            instance.completed = True
            instance.application.status = '2'
            instance.save()
            instance.application.save()
        if instance.status == '1':
            instance.completed = True
            instance.application.status = '1'
            instance.application.paid = True
            instance.save()
            instance.application.save()

applicant/forms.py
from django import forms
from django.forms import ModelForm
from django.forms.models import inlineformset_factory
from .models import ApplicantPrevEducation, ApplicantProfile


class DateInput(forms.DateInput):
    input_type = 'date'


class ApplicantProfileForm(ModelForm):
    present_address = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))
    permanent_address = forms.CharField(
        widget=forms.Textarea(attrs={'rows': 3, 'cols': 40}))

    class Meta:
        model = ApplicantProfile
        exclude = ('owner',)
        widgets = {
            'birth_date': DateInput(),
        }


class ApplicantPrevEducationForm(ModelForm):
    class Meta:
        model = ApplicantPrevEducation
        fields = '__all__'


ApplicantPrevEducationFormSet = inlineformset_factory(
    ApplicantProfile, ApplicantPrevEducation, form=ApplicantPrevEducationForm, extra=1)

transaction/forms.py
from django import forms
from django.forms import ModelForm
from .models import InstitutionTransactionMethod, ApplicationPayment


class InstitutionTransactionMethodForm(ModelForm):
    class Meta:
        model = InstitutionTransactionMethod
        exclude = ('institute',)


class ApplicationPaymentForm(ModelForm):
    class Meta:
        model = ApplicationPayment
        exclude = ('application', 'owner', 'institute',
                   'status', 'completed', 'cancel', 'pending',)

    def __init__(self, *args, **kwargs):
        self.transaction_method = kwargs.pop('transaction_method', None)
        super(ApplicationPaymentForm, self).__init__(*args, **kwargs)
        self.fields['payment_method'] = forms.ModelChoiceField(
            queryset=self.transaction_method)

templates/applicant/transaction/pay_fee.html
{% extends "applicant_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    <h3>Pay Fee For {{institute_obj.institute_name}}--Amount : {{institute_obj.application_fee}}</h3>
                </div>
                <div class="card-body">
                    <form action="{% url 'transaction:pay_application_fee' application_id institute_obj.id  %}" method="POST" novalidate>
                        {% csrf_token %}
                        {{application_payment_form|crispy}}

                        <input type="submit" value="Pay">
                    </form>

                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card p-2">
                <div class="card-header">
                    <h1 class="lead text-dark font-weight-bold text-center">Instruction</h1>
                </div>
                <div class="card-body" class="lead text-center font-weight-bold text-dark">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Reference Number : <span id="ref_number"></span></li>
                        <li class="list-group-item">Counter Number : <span id="counter_num"></span></li>
                    </ul>
                    <p id="instruction">

                    </p>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}


{% block script %}
<script>
    $("#id_payment_method").change(function () {
        var payment_method_id =  $(this).val()
        $.ajax({
            url: `/transaction/applicant/transaction/details/${payment_method_id}`,
            success: function (data) {
                data.forEach( function(element, index) {
                    $("#ref_number").text(element.fields.reference_id)
                    $("#counter_num").text(element.fields.counter_no)
                    $("#instruction").text(element.fields.instruction)
                });
            },
            error : function(err) {
                console.log(err);
            }
      });

    });
</script>
{% endblock script %}

templates/applicant/transaction/payment_list.html
{% extends "applicant_base.html" %}

{% load crispy_forms_tags %}

{% block title %}
    {{title}}
{% endblock title %}

{% block content %}
    <div class="row">
        <div class="col-md-10 mx-auto">
            <div class="card">
                <div class="card-header">
                    <h3>Payment List</h3>
                </div>
                <div class="card-body">

                    <table id="datatable" class="table table-striped dt-responsive nowrap" style="border-collapse: collapse; border-spacing: 0; width: 100%;">
                        <thead>
                            <tr>
                                <th>Student Name</th>
                                <th>Institute Name</th>
                                <th>Level</th>
                                <th>Subject</th>
                                <th>Fee</th>
                                <th>Transaction Number</th>
                                <th>Status</th>
                                <th>Created At</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for payment in payment_list %}
                                <tr>
                                    <td>{{payment.application.applicant.student_name}}</td>
                                    <td>{{payment.institute.institute_name}}</td>
                                    <td>{{payment.application.get_level_display}}</td>
                                    <td>{{payment.application.subject.subject_name}}</td>
                                    <td>{{payment.institute.application_fee}}</td>
                                    <td>{{payment.transaction_number}}</td>
                                    <td>{{payment.get_status_display}}</td>
                                    <td>{{payment.created_at}}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>

            {% include 'partials/_pagination.html' %}
        </div>
    </div>
{% endblock content %}